# Generated by Django 4.1.5 on 2023-01-04 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('teacher_name', models.CharField(max_length=30)),
                ('student_count', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdname', models.CharField(max_length=100)),
                ('stdage', models.IntegerField()),
                ('stdmail', models.EmailField(max_length=254)),
                ('stdclass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentdata.classdetails')),
            ],
        ),
    ]
